### ISSUE TITLE
Unable to sign-in

### ISSUE THREAD

**Issue by ghost** [fs-webcomponents/sample-app#9]
First off, I'm not sure if this project is open to public contributions. If not, ignore this. When I attempt to login after starting the server I get the following error `Oauth2 error: redirect URI not configured correctly` on the familysearch.org page that is loaded. I found the place where the redirect URI can be set, but I'm guessing I need to be on a specific domain for it to work. I am currently building apps with Polymer and would be very interested in contributing however I can.

**Comment by misbach** [comment]
@brycethorup We would love your contributions. You need to create a developer account to obtain an app key, and then register an oauth callback URL. https://familysearch.org/developers/

**Comment by justincy** [comment]
@brycethorup Still need help with his?

**Comment by ghost** [comment]
No, I got it working. I just haven't had a chance to do much with it yet.
